/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_uitest_EyeActivity */

#ifndef _Included_com_example_uitest_EyeActivity
#define _Included_com_example_uitest_EyeActivity
#ifdef __cplusplus


extern "C" {
#endif

/*
* Class:     com_example_uitest_EyeActivity
* Method:    stringFromJNI
* Signature: ()Ljava/lang/String;
*/
JNIEXPORT jstring JNICALL Java_com_example_uitest_EyeActivity_stringFromJNI
        (JNIEnv *, jobject);

/*
 * Class:     com_example_uitest_EyeActivity
 * Method:    decode
 * Signature: ([BLjava/lang/Object;II)I
 */
JNIEXPORT jint JNICALL Java_com_example_uitest_EyeActivity_decode
        (JNIEnv *, jobject, jbyteArray, jobject, jint , jint , jint , jint,
         jint, jint,jobject,jobject, jobject );

/*
 * Class:     com_example_uitest_EyeActivity
 * Method:    loadShapeModel
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_example_uitest_EyeActivity_loadShapeModel
(JNIEnv *env, jobject obj, jobject assetManager, jstring fileName);

/*
 * Class:     com_example_uitest_EyeActivity
 * Method:    loadFaceModel
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_example_uitest_EyeActivity_loadFaceModel
(JNIEnv *, jobject, jstring);

/*
 * Class:     com_example_uitest_EyeActivity
 * Method:    loadMedModel
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_example_uitest_EyeActivity_loadMedModel
(JNIEnv *, jobject, jstring);



#ifdef __cplusplus
}
#endif
#endif
